baseURL = "https://twentynineteen-hugo-demo.netlify.com/"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "twentynineteen-hugo"

[outputs]
Home = ["HTML", "RSS", "JSON"]

[params]
privacy_link = "/privacy/"
description = "TwentyNineteen ported from WordPress"

[menu]
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 0
  [[menu.social]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/jeremybise/twentynineteen-hugo"
  [[menu.social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/gohugoio"
  [[menu.footer]]
    name = "About"
    url = "/about/"
    weight = 1